-- ---------------------------------------------------------------------
-- extra_schema_31.sql
-- SUPERSEDED — do not run this file. It has already done its job once.
--
-- This originally shifted the GED timetable +40 minutes RELATIVE to
-- whatever time was already in the database. Running it more than once
-- keeps shifting the schedule further every time, which is exactly what
-- caused the timetable to repeatedly drift later and later in practice.
--
-- extra_schema_33.sql replaced this with an ABSOLUTE fix — it sets each
-- period to an exact, correct time regardless of history, so it can be
-- safely run again any time the schedule looks wrong. If the timetable
-- is ever off, run extra_schema_33.sql, never this file.
--
-- The statement below is intentionally a no-op so that even if this
-- file is run again by accident, it changes nothing.
-- ---------------------------------------------------------------------
select 1 where false;
