-- =====================================================================
-- WAAPC Training Centre — Seed built-in question bank into `questions`
-- Auto-generated from the prototype's hardcoded QUESTION_BANKS. Run this
-- ONCE, after schema.sql and extra_schema.sql, in the Supabase SQL Editor.
-- Safe to re-run: skips rows that already exist for the same subject+text.
-- Total: 9 tests, 35 subject groups, 449 questions.
-- =====================================================================

insert into questions (subject_id, question_text, options, correct_index)
select sub.id, v.question_text, v.options, v.correct_index
from (values
  ('GED', 'Reasoning Through Language Arts', 'Choose the sentence that correctly fixes the run-on: ''The exam was difficult many students struggled.''', '["The exam was difficult many, students struggled.","The exam was difficult, many students struggled.","The exam, was difficult many students struggled.","The exam was difficult; many students struggled."]'::jsonb, 3),
  ('GED', 'Reasoning Through Language Arts', 'Choose the sentence with correct subject-verb agreement.', '["Each of the students having a book.","Each of the student has a book.","Each of the students have a book.","Each of the students has a book."]'::jsonb, 3),
  ('GED', 'Reasoning Through Language Arts', 'Which sentence uses the apostrophe correctly?', '["The dogs'' wagged its tail.","The dog wag''s its tail.","The dog wagged its tail.","The dog wagged it''s tail."]'::jsonb, 2),
  ('GED', 'Reasoning Through Language Arts', 'Choose the option with correct parallel structure: ''She likes hiking, to swim, and biking.''', '["She like hiking, swim, and biking.","She likes hiking, to swim, and to bike.","She likes to hike, swimming, and to bike.","She likes hiking, swimming, and biking."]'::jsonb, 3),
  ('GED', 'Reasoning Through Language Arts', 'In ''The senator''s argument was compelling, but ultimately specious,'' the word ''specious'' most nearly means:', '["Convincing","Simple","Lengthy","Deceptive or misleading"]'::jsonb, 3),
  ('GED', 'Reasoning Through Language Arts', 'A passage focuses on the causes, events, and aftermath of a drought, centering on farmer migration. What is its main idea?', '["The economic and social impact of the drought on farming communities","Modern irrigation technology","A biography of a farmer","Weather patterns in general"]'::jsonb, 0),
  ('GED', 'Reasoning Through Language Arts', 'An author writes: ''Our city must act now, before the river rises further.'' This is primarily meant to:', '["Persuade the reader to support urgent action","Describe a scene neutrally","Entertain the reader","Provide historical background only"]'::jsonb, 0),
  ('GED', 'Reasoning Through Language Arts', 'Choose the sentence with correct verb tense.', '["By the time she arrive, the meeting had started.","By the time she arrived, the meeting had already started.","By the time she arrived, the meeting already started.","By the time she arrived, the meeting starts."]'::jsonb, 1),
  ('GED', 'Reasoning Through Language Arts', 'Choose the sentence with correct pronoun-antecedent agreement.', '["Each student must bring his or her own laptop.","Every student must bring our own laptop.","Each students must bring their own laptop.","Each student must bring their own laptop."]'::jsonb, 0),
  ('GED', 'Reasoning Through Language Arts', 'Which of the following is a complete sentence, not a fragment?', '["Because the rain would not stop.","Although the results were surprising.","Running through the park every morning.","The committee reviewed the proposal carefully."]'::jsonb, 3),
  ('GED', 'Reasoning Through Language Arts', 'Choose the best topic sentence for a paragraph about renewable energy adoption in rural areas.', '["Rural communities are increasingly adopting renewable energy to reduce costs and improve reliability.","The weather was sunny yesterday.","Energy is important.","Solar panels come in many colors."]'::jsonb, 0),
  ('GED', 'Reasoning Through Language Arts', 'Identify the sentence fragment.', '["Although the team practiced for hours.","They won because they practiced.","The team practiced, and they won.","The team practiced for hours."]'::jsonb, 0),
  ('GED', 'Reasoning Through Language Arts', 'Which version uses the more formal register appropriate for a business report?', '["It was totally wrong, no cap.","The numbers were kind of off, you know?","The figures showed a notable discrepancy.","Stuff didn''t add up right."]'::jsonb, 2),
  ('GED', 'Reasoning Through Language Arts', 'Choose the transition word that best connects two contrasting ideas: ''The company invested heavily in training. ____, turnover remained high.''', '["Similarly","In addition","However","Therefore"]'::jsonb, 2),
  ('GED', 'Reasoning Through Language Arts', 'Which sentence best presents evidence supporting the claim that a policy was effective?', '["The policy was good.","People liked the policy.","The policy was announced in March.","After the policy passed, unemployment fell by 4% within a year."]'::jsonb, 3),
  ('GED', 'Reasoning Through Language Arts', 'Choose the correctly capitalized sentence.', '["My aunt Visited Paris in the Summer.","My aunt visited Paris in the summer.","My Aunt visited Paris in the summer.","my Aunt visited paris in the Summer."]'::jsonb, 1),
  ('GED', 'Reasoning Through Language Arts', 'Which sentence corrects the comma splice: ''The rain stopped, we went outside.''', '["The rain stopped, we, went outside.","The rain stopped we, went outside.","The rain, stopped we went outside.","The rain stopped so we went outside."]'::jsonb, 3),
  ('GED', 'Reasoning Through Language Arts', 'Choose the word that best completes: ''The committee''s decision was ______; no one expected such a bold move.''', '["routine","forgettable","unprecedented","predictable"]'::jsonb, 2),
  ('GED', 'Reasoning Through Language Arts', 'Identify the best paraphrase of: ''Despite the setback, the team pressed on.''', '["The team caused the setback.","The team was unaffected by anything.","The team quit after the setback.","The team continued working even after facing a difficulty."]'::jsonb, 3),
  ('GED', 'Reasoning Through Language Arts', 'Which sentence demonstrates correct use of a semicolon?', '["I have a test tomorrow; I need to study tonight.","I have a test tomorrow, I need to study tonight;","I have a test; tomorrow I need to study tonight.","I have; a test tomorrow I need to study tonight."]'::jsonb, 0),
  ('GED', 'Mathematical Reasoning', 'Solve: 5x - 7 = 18', '["x = 5","x = 25","x = -5","x = 3"]'::jsonb, 0),
  ('GED', 'Mathematical Reasoning', 'Evaluate: 2(3 + 4)^2 - 10', '["78","68","98","88"]'::jsonb, 3),
  ('GED', 'Mathematical Reasoning', 'What is 40% of 250?', '["110","120","100","90"]'::jsonb, 2),
  ('GED', 'Mathematical Reasoning', 'Simplify: (x^2)(x^5)', '["x^-3","x^7","x^3","x^10"]'::jsonb, 1),
  ('GED', 'Mathematical Reasoning', 'Solve for y: 2y/3 = 8', '["16","12","8","24"]'::jsonb, 1),
  ('GED', 'Mathematical Reasoning', 'Find the area of a rectangle with length 8 and width 5.', '["40","45","13","20"]'::jsonb, 0),
  ('GED', 'Mathematical Reasoning', 'Find the perimeter of a square with side length 6.', '["18","24","12","36"]'::jsonb, 1),
  ('GED', 'Mathematical Reasoning', 'What is the formula for the circumference of a circle?', '["πd/2","2πr","πr^2","r^2"]'::jsonb, 1),
  ('GED', 'Mathematical Reasoning', 'Find the mean of: 4, 8, 6, 10, 12', '["7","9","8","10"]'::jsonb, 2),
  ('GED', 'Mathematical Reasoning', 'Find the median of: 3, 7, 9, 15, 20', '["7","9","15","10"]'::jsonb, 1),
  ('GED', 'Mathematical Reasoning', 'Solve the inequality: 3x + 2 > 11', '["x > 3","x > 13/3","x > 11","x < 3"]'::jsonb, 0),
  ('GED', 'Mathematical Reasoning', 'Convert 3/8 to a decimal.', '["0.38","0.375","0.475","0.325"]'::jsonb, 1),
  ('GED', 'Mathematical Reasoning', 'Find the slope of the line through (1, 2) and (3, 8).', '["3","2","6","1/3"]'::jsonb, 0),
  ('GED', 'Mathematical Reasoning', 'A right triangle has legs of 6 and 8. What is the length of the hypotenuse?', '["10","9","12","14"]'::jsonb, 0),
  ('GED', 'Mathematical Reasoning', 'Solve the system: x + y = 10, x - y = 2. What is x?', '["8","6","4","5"]'::jsonb, 1),
  ('GED', 'Mathematical Reasoning', 'Solve: 4(x - 2) = 20', '["x = 5","x = 8","x = 6","x = 7"]'::jsonb, 3),
  ('GED', 'Mathematical Reasoning', 'What is 3^4?', '["64","81","12","27"]'::jsonb, 1),
  ('GED', 'Mathematical Reasoning', 'Convert 0.25 to a fraction.', '["1/4","1/5","1/2","2/5"]'::jsonb, 0),
  ('GED', 'Mathematical Reasoning', 'A car travels 150 miles in 3 hours. What is its average speed?', '["45 mph","50 mph","55 mph","60 mph"]'::jsonb, 1),
  ('GED', 'Mathematical Reasoning', 'Find the volume of a cube with side length 4.', '["48","16","32","64"]'::jsonb, 3),
  ('GED', 'Science', 'Which organelle controls cell activities and contains DNA?', '["Vacuole","Ribosome","Nucleus","Mitochondria"]'::jsonb, 2),
  ('GED', 'Science', 'Photosynthesis primarily occurs in which part of a plant cell?', '["Nucleus","Chloroplast","Mitochondria","Cell wall"]'::jsonb, 1),
  ('GED', 'Science', 'What type of energy is stored in the chemical bonds of food?', '["Nuclear","Thermal","Chemical","Kinetic"]'::jsonb, 2),
  ('GED', 'Science', 'Newton''s first law of motion describes:', '["Inertia — an object stays at rest or in motion unless acted on by a force","Gravity","Action and reaction forces","Acceleration equals force divided by mass"]'::jsonb, 0),
  ('GED', 'Science', 'What is the pH of a neutral solution?', '["0","7","1","14"]'::jsonb, 1),
  ('GED', 'Science', 'Which layer of Earth is liquid and generates the planet''s magnetic field?', '["Mantle","Inner core","Crust","Outer core"]'::jsonb, 3),
  ('GED', 'Science', 'What is the process by which water changes from liquid to gas called?', '["Sublimation","Precipitation","Evaporation","Condensation"]'::jsonb, 2),
  ('GED', 'Science', 'Which gas makes up the largest percentage of Earth''s atmosphere?', '["Carbon dioxide","Argon","Oxygen","Nitrogen"]'::jsonb, 3),
  ('GED', 'Science', 'Offspring inherit traits from their parents primarily through:', '["Proteins directly","DNA and genes","Enzymes","Hormones"]'::jsonb, 1),
  ('GED', 'Science', 'Which force keeps planets in orbit around the sun?', '["Gravity","Friction","Inertia","Magnetism"]'::jsonb, 0),
  ('GED', 'Science', 'Which type of rock forms from cooled magma or lava?', '["Mineral","Metamorphic","Igneous","Sedimentary"]'::jsonb, 2),
  ('GED', 'Science', 'Which human body system is primarily responsible for gas exchange?', '["Digestive","Respiratory","Nervous","Circulatory"]'::jsonb, 1),
  ('GED', 'Science', 'In an ecosystem, the primary producers are typically:', '["Plants","Decomposers","Carnivores","Herbivores"]'::jsonb, 0),
  ('GED', 'Science', 'Which of these is a renewable energy source?', '["Coal","Natural gas","Petroleum","Solar"]'::jsonb, 3),
  ('GED', 'Science', 'Speed is calculated as:', '["Mass divided by time","Time divided by distance","Distance divided by time","Distance multiplied by time"]'::jsonb, 2),
  ('GED', 'Science', 'Which blood cell type primarily fights infection?', '["White blood cells","Plasma cells only","Red blood cells","Platelets"]'::jsonb, 0),
  ('GED', 'Science', 'What is the primary function of the ozone layer?', '["Absorbing harmful ultraviolet radiation","Producing oxygen","Trapping heat like a greenhouse","Creating wind patterns"]'::jsonb, 0),
  ('GED', 'Science', 'Which of these is an example of a chemical change?', '["Melting of ice","Boiling of water","Breaking of glass","Rusting of iron"]'::jsonb, 3),
  ('GED', 'Science', 'In the water cycle, the process of water vapor turning into liquid droplets is called:', '["Precipitation","Transpiration","Evaporation","Condensation"]'::jsonb, 3),
  ('GED', 'Science', 'Which planet is known for its prominent ring system?', '["Mercury","Saturn","Venus","Mars"]'::jsonb, 1),
  ('GED', 'Social Studies', 'Which document begins with the words ''We the People''?', '["The Declaration of Independence","The Bill of Rights","The Magna Carta","The US Constitution"]'::jsonb, 3),
  ('GED', 'Social Studies', 'The US federal government is divided into how many branches?', '["5","4","2","3"]'::jsonb, 3),
  ('GED', 'Social Studies', 'Which branch of government is responsible for making laws?', '["Judicial","Administrative","Executive","Legislative"]'::jsonb, 3),
  ('GED', 'Social Studies', 'The system of checks and balances is designed to:', '["Balance the federal budget","Give more power to the states","Prevent any one branch from gaining too much power","Create political parties"]'::jsonb, 2),
  ('GED', 'Social Studies', 'Which amendment to the US Constitution abolished slavery?', '["19th Amendment","13th Amendment","15th Amendment","14th Amendment"]'::jsonb, 1),
  ('GED', 'Social Studies', 'In a market economy, prices are primarily determined by:', '["Corporate boards only","Supply and demand","Government decree","Foreign investors"]'::jsonb, 1),
  ('GED', 'Social Studies', 'Which best describes inflation?', '["Stable prices over time","A general increase in prices and a fall in the value of money","A general decrease in prices","An increase in wages only"]'::jsonb, 1),
  ('GED', 'Social Studies', 'The Cold War was primarily a rivalry between:', '["The United States and the Soviet Union","France and Germany","The United Kingdom and Spain","The United States and China"]'::jsonb, 0),
  ('GED', 'Social Studies', 'A country''s GDP measures:', '["The total value of goods and services produced","Total exports only","Total population","Total land area"]'::jsonb, 0),
  ('GED', 'Social Studies', 'Which geographic feature is a landform surrounded by water on three sides?', '["Peninsula","Island","Isthmus","Plateau"]'::jsonb, 0),
  ('GED', 'Social Studies', 'The right to a fair trial is protected under which part of the US Constitution?', '["The Bill of Rights","The Articles of Confederation","The Federalist Papers","The Declaration of Independence"]'::jsonb, 0),
  ('GED', 'Social Studies', 'Which economic system is characterized by private ownership and free markets?', '["Socialism","Capitalism","Communism","Feudalism"]'::jsonb, 1),
  ('GED', 'Social Studies', 'The division of power between national and state governments is called:', '["Autocracy","Anarchy","Federalism","Democracy"]'::jsonb, 2),
  ('GED', 'Social Studies', 'Which of the following was a major cause of World War I?', '["The fall of the Berlin Wall","The Great Depression","The Cuban Missile Crisis","Alliances and nationalism combined with a triggering assassination"]'::jsonb, 3),
  ('GED', 'Social Studies', 'A nation''s balance of trade refers to the difference between:', '["Savings and debt","Taxes and government spending","Wages and prices","The difference between a nation''s exports and imports"]'::jsonb, 3),
  ('GED', 'Social Studies', 'Which of these best defines ''due process''?', '["The requirement to pay taxes","The process of amending the Constitution","The right to vote in elections","The government must follow fair legal procedures before depriving someone of life, liberty, or property"]'::jsonb, 3),
  ('GED', 'Social Studies', 'What economic indicator measures the percentage of the labor force that is jobless and seeking work?', '["Inflation rate","Interest rate","GDP growth rate","Unemployment rate"]'::jsonb, 3),
  ('GED', 'Social Studies', 'The Emancipation Proclamation was issued by which US President?', '["Thomas Jefferson","George Washington","Franklin D. Roosevelt","Abraham Lincoln"]'::jsonb, 3),
  ('GED', 'Social Studies', 'Which of the following is a function of the United Nations?', '["Promoting international peace and cooperation","Setting US tax policy","Enforcing US federal law","Electing US senators"]'::jsonb, 0),
  ('GED', 'Social Studies', 'A tariff is best defined as:', '["A trade agreement between two states","A tax imposed on imported goods","A federal minimum wage law","A type of government subsidy"]'::jsonb, 1),
  ('SAT', 'Reading & Writing', 'Choose the word that best fits: The scientist''s findings were ______ by later research.', '["confused","corroborated","erased","ignored"]'::jsonb, 1),
  ('SAT', 'Reading & Writing', 'Which sentence uses correct subject-verb agreement?', '["The list of items are on the table.","The list of item is on the table.","The list of items is on the table.","The lists of items is on table."]'::jsonb, 2),
  ('SAT', 'Reading & Writing', 'Choose the best transition: ''The bridge was closed for repairs. ____, traffic was rerouted through downtown.''', '["However","For example","As a result","In contrast"]'::jsonb, 2),
  ('SAT', 'Reading & Writing', 'Identify the sentence with correct comma usage.', '["After, the meeting we went to lunch.","After the meeting we went, to lunch.","After the meeting, we went to lunch.","After the meeting we, went to lunch."]'::jsonb, 2),
  ('SAT', 'Reading & Writing', 'Choose the word closest in meaning to ''ambiguous.''', '["Brief","Loud","Unclear","Certain"]'::jsonb, 2),
  ('SAT', 'Reading & Writing', 'Which sentence corrects the misplaced modifier: ''Running quickly, the bus was missed by Sarah.''', '["The bus, running quickly, was missed by Sarah.","Missed by Sarah, running quickly was the bus.","Running quickly, Sarah missed the bus.","Sarah, running quickly the bus was missed."]'::jsonb, 2),
  ('SAT', 'Reading & Writing', 'A passage that presents both sides of an issue before concluding uses a structure best described as:', '["Chronological narrative","Compare and contrast","Cause and effect only","Pure description"]'::jsonb, 1),
  ('SAT', 'Reading & Writing', 'Choose the correct word: ''The committee will ______ its decision by Friday.''', '["announced","announces","announcing","announce"]'::jsonb, 3),
  ('SAT', 'Reading & Writing', 'Which sentence uses correct semicolon usage?', '["The report was thorough, it; covered every department.","The report; was thorough it covered every department.","The report was thorough; it covered every department.","The report was thorough it; covered every department."]'::jsonb, 2),
  ('SAT', 'Reading & Writing', 'Choose the best synonym for ''meticulous.''', '["Quick","Careful and precise","Loud","Careless"]'::jsonb, 1),
  ('SAT', 'Reading & Writing', 'Which sentence correctly uses an em dash?', '["The results were clear —, everyone had improved.","The results were clear — everyone had improved.","The results, were clear — everyone had improved.","The results were clear— everyone, had improved."]'::jsonb, 1),
  ('SAT', 'Reading & Writing', 'Identify the best concluding sentence for a paragraph about the benefits of exercise.', '["Gyms are often crowded in January.","Some people prefer running to swimming.","Exercise can be done indoors or outdoors.","In short, regular exercise offers lasting benefits for both body and mind."]'::jsonb, 3),
  ('SAT', 'Reading & Writing', 'Choose the word that best fits: ''The novel''s plot was ______, keeping readers engaged until the final page.''', '["forgettable","boring","gripping","predictable"]'::jsonb, 2),
  ('SAT', 'Reading & Writing', 'Which sentence avoids redundancy?', '["The final outcome was decided by the judges.","The final outcome result was decided by the judges.","The end final outcome was decided.","The final end result outcome was decided by the judges."]'::jsonb, 0),
  ('SAT', 'Reading & Writing', 'Choose the correct verb form: ''By next year, she ______ her degree.''', '["will have completed","completed","completes","will complete"]'::jsonb, 0),
  ('SAT', 'Math', 'If 2x + 3 = 11, what is x?', '["6","4","5","3"]'::jsonb, 1),
  ('SAT', 'Math', 'What is the value of 5^2 - 3^2?', '["9","34","25","16"]'::jsonb, 3),
  ('SAT', 'Math', 'Simplify: 3(x + 4) - 2x', '["5x + 12","3x + 12","x + 4","x + 12"]'::jsonb, 3),
  ('SAT', 'Math', 'A line has slope 2 and passes through (0,3). What is its equation?', '["y = -2x + 3","y = 3x + 2","y = 2x + 3","y = 2x - 3"]'::jsonb, 2),
  ('SAT', 'Math', 'What is 3/4 expressed as a percentage?', '["65%","70%","80%","75%"]'::jsonb, 3),
  ('SAT', 'Math', 'Solve: x^2 = 49', '["x = -7 only","x = 7 only","x = 7 or x = -7","x = 49"]'::jsonb, 2),
  ('SAT', 'Math', 'If a rectangle''s length is twice its width and the width is 5, what is the area?', '["25","50","100","10"]'::jsonb, 1),
  ('SAT', 'Math', 'What is the value of x if 3x - 4 = 2x + 6?', '["6","10","14","4"]'::jsonb, 1),
  ('SAT', 'Math', 'Simplify: 4x^2 / 2x', '["8x","2x","x","2x^2"]'::jsonb, 1),
  ('SAT', 'Math', 'What is the area of a circle with radius 5? (use pi = 3.14)', '["31.4","50","15.7","78.5"]'::jsonb, 3),
  ('SAT', 'Math', 'If y = 2x^2 and x = 3, what is y?', '["36","18","12","9"]'::jsonb, 1),
  ('SAT', 'Math', 'What is the value of |-7|?', '["14","-7","7","0"]'::jsonb, 2),
  ('SAT', 'Math', 'Solve: (x - 3)(x + 2) = 0', '["x = 3 or x = 2","x = 3 or x = -2","x = -3 or x = 2","x = -3 or x = -2"]'::jsonb, 1),
  ('SAT', 'Math', 'A jacket originally priced at 40,000 CFA is discounted by 25%. What is the new price?', '["28,000 CFA","35,000 CFA","32,000 CFA","30,000 CFA"]'::jsonb, 3),
  ('SAT', 'Math', 'What is the sum of the interior angles of a triangle?', '["360 degrees","270 degrees","180 degrees","90 degrees"]'::jsonb, 2),
  ('ACT', 'English', 'Choose the grammatically correct option.', '["Neither of boys was late.","Neither of the boys was late.","Neither of the boys were late.","Neither of the boy was late."]'::jsonb, 1),
  ('ACT', 'English', 'Which sentence avoids a dangling modifier?', '["Walking to school, the rain began to fall.","Walking to school the rain fell on me it began.","The rain, walking to school, began to fall.","Walking to school, I got caught in the rain."]'::jsonb, 3),
  ('ACT', 'English', 'Choose the correct word: ''The ____ of the policy was immediate.''', '["affect","effect","affected","effecting"]'::jsonb, 1),
  ('ACT', 'English', 'Which punctuation correctly separates two independent clauses?', '["Semicolon","No punctuation","Colon only","Comma alone"]'::jsonb, 0),
  ('ACT', 'English', 'Identify the sentence with correct pronoun case.', '["Him and me went to the store.","He and me went to the store.","He and I went to the store.","Him and I went to the store."]'::jsonb, 2),
  ('ACT', 'English', 'Choose the correct form: ''The team ______ practicing every day.''', '["are","were","is","have"]'::jsonb, 2),
  ('ACT', 'English', 'Identify the correctly punctuated sentence.', '["Although tired she finished, the race.","Although tired, she finished the race.","Although, tired she finished the race.","Although tired she, finished the race."]'::jsonb, 1),
  ('ACT', 'English', 'Choose the word that best fits: ''His argument was ______; it lacked any supporting evidence.''', '["convincing","factual","unsubstantiated","detailed"]'::jsonb, 2),
  ('ACT', 'English', 'Which sentence correctly uses ''its'' vs ''it''s''?', '["Its important to check its battery level.","It''s important to check it''s battery level.","Its important to check it''s battery level.","It''s important to check its battery level."]'::jsonb, 3),
  ('ACT', 'English', 'Choose the sentence with correct word order.', '["She her homework quickly finished.","Quickly she her homework finished.","She quickly finished her homework.","She finished quickly her homework."]'::jsonb, 2),
  ('ACT', 'English', 'Identify the sentence free of redundancy.', '["The plan was finished completely totally.","The plan was completely finished.","The plan, completely, was totally finished.","The plan was completely totally finished."]'::jsonb, 1),
  ('ACT', 'English', 'Choose the correct comparative form: ''This test was ______ than the last one.''', '["harder","most hard","hardest","more harder"]'::jsonb, 0),
  ('ACT', 'Math', 'Solve: 4x - 9 = 15', '["8","6","4","5"]'::jsonb, 1),
  ('ACT', 'Math', 'What is the perimeter of a triangle with sides 5, 6, and 7?', '["17","16","18","19"]'::jsonb, 2),
  ('ACT', 'Math', 'Simplify: (x+3)(x-3)', '["x^2 - 6x - 9","x^2 + 9","x^2 - 9","x^2 + 6x - 9"]'::jsonb, 2),
  ('ACT', 'Math', 'What is the least common multiple of 4 and 6?', '["8","18","12","24"]'::jsonb, 2),
  ('ACT', 'Math', 'Convert 0.6 to a fraction in lowest terms.', '["3/4","3/5","6/10","2/3"]'::jsonb, 1),
  ('ACT', 'Math', 'Solve: 2x^2 = 32', '["x = -8","x = 8","x = 4 or x = -4","x = 16"]'::jsonb, 2),
  ('ACT', 'Math', 'What is the value of 6 factorial divided by 5 factorial?', '["6","120","30","1"]'::jsonb, 0),
  ('ACT', 'Math', 'If a triangle has angles of 50 and 60 degrees, what is the third angle?', '["60 degrees","90 degrees","80 degrees","70 degrees"]'::jsonb, 3),
  ('ACT', 'Math', 'What is the distance between points (0,0) and (3,4)?', '["5","7","6","4"]'::jsonb, 0),
  ('ACT', 'Math', 'Simplify: (3x)(4x^2)', '["12x^2","7x^3","7x^2","12x^3"]'::jsonb, 3),
  ('ACT', 'Math', 'What is 2/5 + 1/5?', '["3/5","1/5","3/10","2/10"]'::jsonb, 0),
  ('ACT', 'Math', 'If f(x) = x^2 - 1, what is f(3)?', '["6","9","10","8"]'::jsonb, 3),
  ('ACT', 'Reading', 'A passage''s tone that is critical but respectful is best described as:', '["Measured","Scathing","Flattering","Indifferent"]'::jsonb, 0),
  ('ACT', 'Reading', 'When an author includes a quotation from an expert, this is primarily meant to:', '["Add humor","Support the argument with authority","Confuse the reader","Contradict the thesis"]'::jsonb, 1),
  ('ACT', 'Reading', 'A passage that moves from general claims to specific examples uses which structure?', '["Circular reasoning","Deductive reasoning","Random ordering","Pure narration"]'::jsonb, 1),
  ('ACT', 'Reading', 'The ''central claim'' of a passage is best described as its:', '["Concluding question","First sentence only","Main argument or thesis","List of examples"]'::jsonb, 2),
  ('ACT', 'Reading', 'An author who presents statistics before making a claim is most likely trying to:', '["Confuse the reader","Avoid making an argument","Entertain with numbers","Establish credibility through evidence"]'::jsonb, 3),
  ('ACT', 'Reading', 'Which best describes a passage''s ''point of view''?', '["The vocabulary level used","The perspective from which the story or argument is presented","The topic of the passage","The length of the passage"]'::jsonb, 1),
  ('ACT', 'Reading', 'A passage that uses ''first, next, finally'' is organized:', '["Chronologically","By comparison","Randomly","By cause and effect only"]'::jsonb, 0),
  ('ACT', 'Reading', 'The best definition of ''context clues'' is:', '["A footnote citation","A dictionary definition","The title of the passage","Hints within the surrounding text that help define an unfamiliar word"]'::jsonb, 3),
  ('ACT', 'Reading', 'Which is an example of a counterargument in a persuasive passage?', '["Acknowledging an opposing view before refuting it","Repeating the main claim","Providing only supporting evidence","Ignoring opposing views entirely"]'::jsonb, 0),
  ('ACT', 'Reading', 'A passage that explains ''because of the drought, crop yields fell'' is demonstrating:', '["Cause and effect","Spatial order","Comparison and contrast","Chronological order"]'::jsonb, 0),
  ('ACT', 'Reading', 'What is the purpose of a thesis statement?', '["To provide a bibliography","To define unfamiliar words","To state the main argument or claim of a passage","To list examples only"]'::jsonb, 2),
  ('ACT', 'Reading', 'Which best describes ''tone'' in a passage?', '["The length of sentences","The author''s attitude toward the subject","The number of paragraphs","The font used"]'::jsonb, 1),
  ('ACT', 'Science', 'In a controlled experiment, the variable that is deliberately changed is called the:', '["Constant","Independent variable","Dependent variable","Control group"]'::jsonb, 1),
  ('ACT', 'Science', 'Which of the following best describes a hypothesis?', '["A random guess with no basis","A testable, educated prediction","A proven law","An unrelated observation"]'::jsonb, 1),
  ('ACT', 'Science', 'A graph showing a steep upward trend generally indicates:', '["Rapid increase over time","No change","Rapid decrease","Cyclical pattern only"]'::jsonb, 0),
  ('ACT', 'Science', 'Which is a valid reason an experiment might be repeated multiple times?', '["To improve reliability of results","To avoid using a control group","To change the hypothesis each time","To eliminate the need for data analysis"]'::jsonb, 0),
  ('ACT', 'Science', 'A scientific ''control group'' is used to:', '["Provide a baseline for comparison against the experimental group","Eliminate the need for a hypothesis","Replace the need for data analysis","Increase the sample size only"]'::jsonb, 0),
  ('ACT', 'Science', 'Which of the following best represents an inverse relationship on a graph?', '["Neither variable changes","As one variable increases, the other decreases","Both variables stay constant","Both variables increase together"]'::jsonb, 1),
  ('ACT', 'Science', 'In an experiment testing plant growth under different light levels, the dependent variable is:', '["Plant growth","Light level","Room temperature","Type of soil"]'::jsonb, 0),
  ('ACT', 'Science', 'Which unit would most likely measure the concentration of a solution?', '["Seconds","Meters","Newtons","Molarity (mol/L)"]'::jsonb, 3),
  ('ACT', 'Science', 'A conclusion in a scientific report should be based primarily on:', '["Assumptions made before the experiment","Popular belief","The data collected during the experiment","The researcher''s personal opinion"]'::jsonb, 2),
  ('ACT', 'Science', 'Which of these represents a qualitative observation?', '["The solution had a pH of 4.5","The sample weighed 12 grams","The temperature was 37 degrees Celsius","The solution turned a deep blue color"]'::jsonb, 3),
  ('ACT', 'Science', 'A scatter plot showing points clustered tightly around a rising line indicates:', '["No correlation","A strong positive correlation","A strong negative correlation","An inverse relationship"]'::jsonb, 1),
  ('ACT', 'Science', 'Why is it important to change only one variable at a time in an experiment?', '["To avoid using a control group","So that any change in results can be attributed to that one variable","To finish the experiment faster","To make the data more complex"]'::jsonb, 1),
  ('IELTS (Academic)', 'Listening', 'In IELTS Listening, how many sections are there?', '["3","5","4","2"]'::jsonb, 2),
  ('IELTS (Academic)', 'Listening', 'IELTS Listening Section 1 is typically:', '["A monologue on an academic subject","A discussion between students","An academic lecture","A conversation in an everyday social context"]'::jsonb, 3),
  ('IELTS (Academic)', 'Listening', 'Which skill is most important for IELTS Listening Section 4?', '["Reading maps","Speaking fluently","Casual conversation","Following an academic monologue and note-taking"]'::jsonb, 3),
  ('IELTS (Academic)', 'Listening', 'The IELTS Listening recording is played only once. This means test-takers should:', '["Read the questions in advance and predict answers","Ask for a replay","Ignore the questions entirely","Wait until the recording ends to read questions"]'::jsonb, 0),
  ('IELTS (Academic)', 'Listening', 'IELTS Listening Section 2 typically involves:', '["An academic lecture","A phone call between businesses","A conversation between four people","A monologue set in an everyday social context, like a talk about local facilities"]'::jsonb, 3),
  ('IELTS (Academic)', 'Listening', 'IELTS Listening Section 3 typically involves:', '["A radio advertisement","A weather report","A monologue on a social topic","A conversation between up to four people in an educational context"]'::jsonb, 3),
  ('IELTS (Academic)', 'Listening', 'When you don''t know an answer during IELTS Listening, you should:', '["Make your best guess and move on to avoid losing time on later questions","Stop and wait for the recording to repeat","Leave immediately without finishing the test","Ask the examiner to repeat the audio"]'::jsonb, 0),
  ('IELTS (Academic)', 'Listening', 'Which strategy helps most with IELTS Listening map or plan questions?', '["Following directions carefully while tracking your position on the map","Ignoring the map entirely","Memorizing the whole map beforehand","Listening only for numbers"]'::jsonb, 0),
  ('IELTS (Academic)', 'Listening', 'In IELTS Listening, spelling of answers like names matters because:', '["Only capitalization matters","Spelling is never checked","Incorrectly spelled answers are marked wrong even if understood correctly","Answers are always given as multiple choice"]'::jsonb, 2),
  ('IELTS (Academic)', 'Listening', 'Which type of question asks you to complete a summary using words from the recording?', '["True/False/Not Given","Sentence or summary completion","Matching questions","Multiple choice"]'::jsonb, 1),
  ('IELTS (Academic)', 'Listening', 'IELTS Listening total test time, including transfer time, is approximately:', '["30 minutes","60 minutes","90 minutes","45 minutes"]'::jsonb, 0),
  ('IELTS (Academic)', 'Listening', 'The best approach before each section begins is to:', '["Quickly preview the upcoming questions","Review your previous answers only","Skip the section overview","Close your eyes and relax"]'::jsonb, 0),
  ('IELTS (Academic)', 'Reading', 'IELTS Academic Reading includes how many passages?', '["1","3","4","2"]'::jsonb, 1),
  ('IELTS (Academic)', 'Reading', '''True/False/Not Given'' questions test the ability to:', '["Identify whether a statement matches, contradicts, or isn''t addressed by the text","Translate vocabulary","Predict the next paragraph","Summarize the whole passage"]'::jsonb, 0),
  ('IELTS (Academic)', 'Reading', 'Skimming a passage before answering questions helps the reader:', '["Memorize every word","Get a general idea of content and structure quickly","Translate the passage","Avoid answering detail questions"]'::jsonb, 1),
  ('IELTS (Academic)', 'Reading', 'IELTS Reading ''matching headings'' questions test the ability to:', '["Count sentences in a paragraph","Memorize vocabulary","Identify the main idea of each paragraph and match it to a heading","Translate the paragraph"]'::jsonb, 2),
  ('IELTS (Academic)', 'Reading', '''Matching information'' questions ask you to:', '["Summarize the whole text","Locate specific information or details in the passage","Provide a personal opinion","Rewrite the passage"]'::jsonb, 1),
  ('IELTS (Academic)', 'Reading', 'Scanning a text is best used to:', '["Memorize the passage","Analyze grammar structures","Quickly locate specific information like dates or names","Understand the overall argument in depth"]'::jsonb, 2),
  ('IELTS (Academic)', 'Reading', 'A ''distractor'' in an IELTS Reading multiple choice question is:', '["An incorrect option designed to seem plausible","A repeated question","The correct answer","A footnote"]'::jsonb, 0),
  ('IELTS (Academic)', 'Reading', 'IELTS Academic Reading passages are typically sourced from:', '["Personal diaries","Social media posts","Books, journals, magazines, and newspapers on academic topics","Advertisements"]'::jsonb, 2),
  ('IELTS (Academic)', 'Reading', 'Which is the best first step when approaching a new Reading passage?', '["Answer questions before reading the passage","Skim the passage and questions to understand the general topic and task type","Read every word slowly from start to finish","Translate the passage first"]'::jsonb, 1),
  ('IELTS (Academic)', 'Reading', 'IELTS Reading total time allowed, including transfer, is:', '["90 minutes","60 minutes","45 minutes","30 minutes"]'::jsonb, 1),
  ('IELTS (Academic)', 'Reading', 'A ''Yes/No/Not Given'' question tests whether a statement:', '["Agrees with, contradicts, or isn''t addressed by the writer''s views","Uses formal language","Matches a heading","Is grammatically correct"]'::jsonb, 0),
  ('IELTS (Academic)', 'Reading', 'The best way to manage time across three IELTS Reading passages is to:', '["Spend all your time on passage one","Allocate roughly equal time per passage, moving on if stuck","Read all three passages fully before answering any question","Skip the hardest passage entirely"]'::jsonb, 1),
  ('IELTS (Academic)', 'Writing', 'IELTS Writing Task 1 (Academic) typically asks candidates to:', '["Summarize a lecture","Write a persuasive essay","Describe a chart, graph, or diagram","Write a short story"]'::jsonb, 2),
  ('IELTS (Academic)', 'Writing', 'IELTS Writing Task 2 requires candidates to:', '["List vocabulary words","Write an essay responding to a point of view, argument, or problem","Describe visual data","Translate a paragraph"]'::jsonb, 1),
  ('IELTS (Academic)', 'Writing', 'A well-organized IELTS essay typically includes:', '["Introduction, body paragraphs, and conclusion","A single long paragraph","Only bullet points","No conclusion"]'::jsonb, 0),
  ('IELTS (Academic)', 'Writing', 'IELTS Writing Task 1 responses should be at least:', '["250 words","150 words","300 words","100 words"]'::jsonb, 1),
  ('IELTS (Academic)', 'Writing', 'IELTS Writing Task 2 responses should be at least:', '["100 words","400 words","150 words","250 words"]'::jsonb, 3),
  ('IELTS (Academic)', 'Writing', 'In Task 1, an ''overview'' paragraph should:', '["Predict future data","List every single data point","Give a personal opinion on the data","Summarize the main trends or key features of the data"]'::jsonb, 3),
  ('IELTS (Academic)', 'Writing', 'Which linking word helps show contrast in an essay?', '["In addition","Whereas","Consequently","Similarly"]'::jsonb, 1),
  ('IELTS (Academic)', 'Writing', 'A common mistake to avoid in Task 2 is:', '["Organizing ideas into paragraphs","Including a conclusion","Using topic sentences","Failing to directly address the essay question"]'::jsonb, 3),
  ('IELTS (Academic)', 'Writing', 'Which is a strong thesis statement for a Task 2 essay about remote work?', '["This essay is about jobs.","Remote work is a topic.","While remote work offers flexibility, it can also weaken workplace collaboration.","People work from home sometimes."]'::jsonb, 2),
  ('IELTS (Academic)', 'Writing', 'Coherence and cohesion in IELTS Writing refers to:', '["How logically ideas are organized and connected","Word count only","Spelling accuracy only","Handwriting neatness"]'::jsonb, 0),
  ('IELTS (Academic)', 'Writing', 'Which of the following best describes ''task achievement'' in Task 1?', '["Covering the key features and data accurately as required by the prompt","Comparing to another chart not given","Writing a long introduction","Including a personal opinion"]'::jsonb, 0),
  ('IELTS (Academic)', 'Writing', 'A good strategy for planning an essay before writing is to:', '["Write the conclusion first","Skip planning to save time","Start writing immediately without a plan","Briefly outline main points for each paragraph"]'::jsonb, 3),
  ('IELTS (Academic)', 'Speaking', 'IELTS Speaking Part 2 is also known as the:', '["Discussion","Written response","Long turn (cue card)","Interview"]'::jsonb, 2),
  ('IELTS (Academic)', 'Speaking', 'IELTS Speaking Part 3 typically involves:', '["Reading aloud","A listening exercise","Writing an essay","A deeper discussion of the Part 2 topic''s themes"]'::jsonb, 3),
  ('IELTS (Academic)', 'Speaking', 'Fluency and coherence in IELTS Speaking refers mainly to:', '["Using the most complex vocabulary possible","Speaking as quickly as possible","Memorizing scripted answers","Speaking smoothly and logically without excessive hesitation"]'::jsonb, 3),
  ('IELTS (Academic)', 'Speaking', 'IELTS Speaking Part 1 typically covers:', '["Abstract social issues","A written response task","A long, uninterrupted monologue","Familiar topics like home, work, studies, and interests"]'::jsonb, 3),
  ('IELTS (Academic)', 'Speaking', 'During the 1-minute preparation time in Part 2, candidates should:', '["Remain silent and think only","Ask the examiner questions","Jot down brief notes on key points to mention","Write a full script word for word"]'::jsonb, 2),
  ('IELTS (Academic)', 'Speaking', 'Which is an example of a discourse marker useful in speaking?', '["A grammar rule","A pronunciation symbol","A vocabulary list","''Well, actually...'' to introduce a thought"]'::jsonb, 3),
  ('IELTS (Academic)', 'Speaking', 'Lexical resource in IELTS Speaking refers to:', '["The range and appropriateness of vocabulary used","Volume of speech","Speed of speech","Body language"]'::jsonb, 0),
  ('IELTS (Academic)', 'Speaking', 'Pronunciation scoring in IELTS Speaking considers:', '["Having a native-like accent only","Reading aloud perfectly","Clarity, intonation, and stress patterns that support understanding","Speaking as loudly as possible"]'::jsonb, 2),
  ('IELTS (Academic)', 'Speaking', 'If a candidate doesn''t understand a question, they should:', '["Guess and change topics","Politely ask the examiner to repeat or clarify it","End the interview early","Stay silent"]'::jsonb, 1),
  ('IELTS (Academic)', 'Speaking', 'Grammatical range and accuracy in Speaking assesses:', '["Speed of response","Vocabulary size only","Only tense usage","The variety and correctness of grammar structures used"]'::jsonb, 3),
  ('IELTS (Academic)', 'Speaking', 'A good way to extend an answer in Part 1 is to:', '["Answer with only ''yes'' or ''no''","Give a brief reason or example after the direct answer","Repeat the question back","Change the subject entirely"]'::jsonb, 1),
  ('IELTS (Academic)', 'Speaking', 'IELTS Speaking is conducted:', '["In a group of test-takers","Via a recorded voicemail only","Entirely in written form","Face-to-face or via video with a single examiner"]'::jsonb, 3),
  ('TOEFL', 'Reading', 'TOEFL Reading passages are primarily:', '["Personal letters","Casual conversations","Advertisements","Academic, textbook-style passages"]'::jsonb, 3),
  ('TOEFL', 'Reading', 'A TOEFL Reading ''inference'' question asks the test-taker to:', '["Find an exact quote","Count paragraphs","Translate a word","Determine information implied but not directly stated"]'::jsonb, 3),
  ('TOEFL', 'Reading', 'Vocabulary questions in TOEFL Reading typically ask you to:', '["Identify the closest meaning of a word as used in context","Define a word using a dictionary","Spell the word correctly","Translate the word"]'::jsonb, 0),
  ('TOEFL', 'Reading', 'TOEFL Reading passages are typically about how many words long?', '["About 50 words","About 100 words","About 700 words","About 2000 words"]'::jsonb, 2),
  ('TOEFL', 'Reading', 'A ''sentence simplification'' question asks you to identify:', '["The passage''s title","A grammar error","The longest sentence in the passage","Which answer choice best captures the essential meaning of a highlighted sentence"]'::jsonb, 3),
  ('TOEFL', 'Reading', 'Which best describes a ''rhetorical purpose'' question?', '["The publication date","The passage''s word count","The literal meaning of a word","Why the author included a specific detail or paragraph"]'::jsonb, 3),
  ('TOEFL', 'Reading', 'TOEFL Reading includes how many passages typically?', '["1 passage","3 to 4 passages","10 passages","2 passages"]'::jsonb, 1),
  ('TOEFL', 'Reading', 'A prose summary question asks test-takers to:', '["Count paragraphs","Translate difficult vocabulary","Select the main ideas that best summarize the passage","Identify the author''s nationality"]'::jsonb, 2),
  ('TOEFL', 'Reading', 'Which strategy helps most with TOEFL Reading vocabulary questions?', '["Using surrounding context to infer meaning","Memorizing a dictionary beforehand","Skipping vocabulary questions entirely","Guessing without reading context"]'::jsonb, 0),
  ('TOEFL', 'Reading', 'A ''reference'' question in TOEFL Reading typically asks about:', '["The passage''s structure only","What a pronoun like ''it'' or ''they'' refers to in the passage","The main idea only","The author''s opinion"]'::jsonb, 1),
  ('TOEFL', 'Reading', 'Insert-text questions in TOEFL Reading ask candidates to:', '["Summarize a paragraph","Translate a sentence","Delete an irrelevant sentence","Determine the best place to insert a given sentence into the passage"]'::jsonb, 3),
  ('TOEFL', 'Reading', 'TOEFL Reading passages are drawn from:', '["Introductory academic textbooks across various subjects","Fictional short stories","Advertisements","Personal blogs"]'::jsonb, 0),
  ('TOEFL', 'Listening', 'TOEFL Listening includes lectures and:', '["Weather reports","Song lyrics","Conversations, often in an academic setting like a professor''s office","Radio advertisements"]'::jsonb, 2),
  ('TOEFL', 'Listening', 'Taking notes during TOEFL Listening passages is:', '["Irrelevant to scoring","Not allowed","Encouraged, since audio is played only once","Only for the Speaking section"]'::jsonb, 2),
  ('TOEFL', 'Listening', 'A TOEFL Listening question asking about a speaker''s attitude is testing:', '["Ability to infer tone and opinion from speech","Grammar rules","Reading speed","Vocabulary memorization"]'::jsonb, 0),
  ('TOEFL', 'Listening', 'TOEFL Listening lectures are typically about:', '["Academic subjects delivered in a classroom-like setting","Weather reports","Casual chats between friends","Radio commercials"]'::jsonb, 0),
  ('TOEFL', 'Listening', 'A TOEFL Listening ''function'' question asks about:', '["The literal words spoken only","The recording''s length","The speaker''s nationality","Why a speaker said something, their purpose"]'::jsonb, 3),
  ('TOEFL', 'Listening', 'TOEFL Listening conversations often take place in settings such as:', '["A hospital emergency room","A courtroom","A television studio","A professor''s office or a campus service desk"]'::jsonb, 3),
  ('TOEFL', 'Listening', 'Which is a useful listening strategy for TOEFL lectures?', '["Memorizing every word verbatim","Noting the main topic and key supporting points as you listen","Ignoring examples given by the speaker","Focusing only on the introduction"]'::jsonb, 1),
  ('TOEFL', 'Listening', 'TOEFL Listening ''organization'' questions ask about:', '["How the lecture''s ideas are structured, such as compare-contrast or cause-effect","The pronunciation of the speaker","The speaker''s tone of voice only","The recording''s file format"]'::jsonb, 0),
  ('TOEFL', 'Listening', 'A replay feature in TOEFL Listening allows the test-taker to:', '["Replay the entire test from the beginning","Skip the section entirely","Re-listen to a portion of the audio for a specific question type","Change their earlier answers freely"]'::jsonb, 2),
  ('TOEFL', 'Listening', 'TOEFL Listening tests comprehension of both explicit information and:', '["Written transcripts only","Background music","Implied meaning and speaker attitude","Video content"]'::jsonb, 2),
  ('TOEFL', 'Listening', 'Which best describes an academic discussion segment in TOEFL Listening?', '["A professor and students discussing course-related content","An advertisement jingle","A private phone call","A weather forecast"]'::jsonb, 0),
  ('TOEFL', 'Listening', 'The purpose of note-taking during TOEFL Listening is to:', '["Help recall key details and structure when answering questions","Replace the need to listen carefully","Translate the audio","Avoid answering questions"]'::jsonb, 0),
  ('TOEFL', 'Speaking', 'TOEFL Speaking includes independent and:', '["Integrated tasks that combine reading/listening with speaking","Group discussion tasks","Written response tasks","Multiple choice tasks"]'::jsonb, 0),
  ('TOEFL', 'Speaking', 'An ''independent speaking task'' in TOEFL asks the candidate to:', '["Give a personal opinion or experience without a reading/listening source","Summarize a lecture","Translate a conversation","Read a passage aloud"]'::jsonb, 0),
  ('TOEFL', 'Speaking', 'TOEFL Speaking Task 1, the independent task, typically gives you how much preparation time?', '["15 seconds","No preparation time","1 minute","5 minutes"]'::jsonb, 0),
  ('TOEFL', 'Speaking', 'TOEFL integrated speaking tasks may ask candidates to:', '["Write an essay instead of speaking","Debate with another test-taker","Summarize a short reading and a related lecture, then respond","Give a personal life story"]'::jsonb, 2),
  ('TOEFL', 'Speaking', 'TOEFL Speaking responses are typically how long?', '["5 minutes","3 minutes","45 to 60 seconds","10 seconds"]'::jsonb, 2),
  ('TOEFL', 'Speaking', 'Which delivery trait is scored in TOEFL Speaking?', '["Length of response only","Accent similarity to a native speaker","Clear pronunciation and natural pacing","Volume alone"]'::jsonb, 2),
  ('TOEFL', 'Speaking', 'Topic development in TOEFL Speaking scoring refers to:', '["How well ideas are elaborated and logically connected","How loudly the candidate speaks","Whether the candidate memorized a script","How quickly the candidate finishes"]'::jsonb, 0),
  ('TOEFL', 'Speaking', 'In an integrated speaking task combining a reading and lecture, the lecture often:', '["Is unrelated to the reading","Repeats the reading exactly","Replaces the need to listen to the reading","Provides examples or a differing perspective related to the reading"]'::jsonb, 3),
  ('TOEFL', 'Speaking', 'A good technique before responding in TOEFL Speaking is to:', '["Repeat the question verbatim as the whole answer","Quickly organize key points mentally or with brief notes","Ask to skip the task","Stay silent until time runs out"]'::jsonb, 1),
  ('TOEFL', 'Speaking', 'Which is scored in TOEFL Speaking alongside delivery and language use?', '["Handwriting","Spelling","Topic development","Vocabulary list memorization"]'::jsonb, 2),
  ('TOEFL', 'Speaking', 'TOEFL Speaking is recorded and later:', '["Broadcast publicly","Shared with other test-takers","Scored by trained raters and/or automated scoring","Deleted immediately without scoring"]'::jsonb, 2),
  ('TOEFL', 'Speaking', 'The best way to practice for TOEFL Speaking is to:', '["Only write essays instead","Practice speaking on varied topics within a strict time limit","Memorize a single universal answer","Avoid speaking practice altogether"]'::jsonb, 1),
  ('TOEFL', 'Writing', 'The TOEFL Integrated Writing task requires the test-taker to:', '["Write a personal narrative","Describe a photograph","Summarize how a lecture relates to a reading passage","Translate a document"]'::jsonb, 2),
  ('TOEFL', 'Writing', 'The TOEFL Independent Writing task asks candidates to:', '["Write an essay expressing and supporting an opinion on a topic","Proofread a passage","Summarize a lecture","Describe a graph"]'::jsonb, 0),
  ('TOEFL', 'Writing', 'TOEFL Integrated Writing responses are typically how long?', '["500 words","150 to 225 words","50 words","1000 words"]'::jsonb, 1),
  ('TOEFL', 'Writing', 'TOEFL Independent Writing responses should typically be at least:', '["500 words","150 words","100 words","300 words"]'::jsonb, 3),
  ('TOEFL', 'Writing', 'In Integrated Writing, a common task structure is to explain how the lecture:', '["Is entirely unrelated to the reading","Simply repeats the reading","Replaces the reading''s argument entirely","Challenges or casts doubt on points made in the reading"]'::jsonb, 3),
  ('TOEFL', 'Writing', 'Which is an important skill for TOEFL Integrated Writing?', '["Copying full sentences from the reading","Ignoring the lecture entirely","Accurately paraphrasing rather than copying source language","Writing only your personal opinion"]'::jsonb, 2),
  ('TOEFL', 'Writing', 'A strong TOEFL Independent Writing essay typically includes:', '["No paragraph breaks","Random unrelated examples","A clear thesis, organized body paragraphs, and a conclusion","Only bullet points"]'::jsonb, 2),
  ('TOEFL', 'Writing', 'Which scoring criterion applies to TOEFL Writing?', '["Handwriting neatness","Drawing ability","Spoken pronunciation","Development, organization, and language use"]'::jsonb, 3),
  ('TOEFL', 'Writing', 'A common mistake in Integrated Writing is:', '["Using paraphrased language","Failing to connect the lecture''s points back to the reading","Organizing ideas clearly","Including specific details from both sources"]'::jsonb, 1),
  ('TOEFL', 'Writing', 'In TOEFL Writing, revising for grammar and word choice mainly improves:', '["Language use scoring","Typing speed","Only word count","Font formatting"]'::jsonb, 0),
  ('TOEFL', 'Writing', 'A good opening strategy for Independent Writing is to:', '["State a clear position on the prompt","Begin with irrelevant background only","Copy the prompt word for word as the whole introduction","Ask the reader a rhetorical question with no answer"]'::jsonb, 0),
  ('TOEFL', 'Writing', 'The main purpose of TOEFL Writing tasks is to assess:', '["Handwriting style","The ability to write clearly and effectively in an academic context","Memorized vocabulary lists only","Typing speed"]'::jsonb, 1),
  ('Intensive English Training', 'Grammar & Structures', 'Choose the correct form: ''She ____ to the market every Saturday.''', '["go","going","gone","goes"]'::jsonb, 3),
  ('Intensive English Training', 'Grammar & Structures', 'Choose the correct sentence.', '["I am living here since 2019.","I have been living here since 2019.","I lived here since 2019.","I live here since 2019."]'::jsonb, 1),
  ('Intensive English Training', 'Grammar & Structures', 'Which sentence uses the correct conditional form? ''If it rains, I ____ stay home.''', '["was","had","will","would"]'::jsonb, 2),
  ('Intensive English Training', 'Grammar & Structures', 'Choose the correctly formed passive sentence.', '["The letter written by John.","John was write the letter.","The letter is wrote by John.","The letter was written by John."]'::jsonb, 3),
  ('Intensive English Training', 'Grammar & Structures', 'Choose the correct form: ''They ______ finished their homework already.''', '["have","having","has","had have"]'::jsonb, 0),
  ('Intensive English Training', 'Grammar & Structures', 'Which sentence correctly uses the past continuous?', '["I studying was when you called.","I am studying when you called yesterday.","I was studying when you called.","I study was when you called."]'::jsonb, 2),
  ('Intensive English Training', 'Grammar & Structures', 'Choose the correct comparative: ''This book is ______ than that one.''', '["more interesting","interestinger","interesting more","most interesting"]'::jsonb, 0),
  ('Intensive English Training', 'Grammar & Structures', 'Which sentence uses the correct modal verb for advice?', '["You must to see a doctor.","You should to see a doctor.","You should see a doctor.","You seeing a doctor should."]'::jsonb, 2),
  ('Intensive English Training', 'Grammar & Structures', 'Choose the correct question form.', '["Where you do live?","Where do you live?","Where does you live?","Where you live do?"]'::jsonb, 1),
  ('Intensive English Training', 'Grammar & Structures', 'Which sentence correctly uses the present perfect?', '["I have visit Paris twice.","I has visited Paris twice.","I have visited Paris twice.","I having visited Paris twice."]'::jsonb, 2),
  ('Intensive English Training', 'Grammar & Structures', 'Choose the correctly formed negative sentence.', '["She not likes coffee.","She doesn''t like coffee.","She isn''t likes coffee.","She don''t likes coffee."]'::jsonb, 1),
  ('Intensive English Training', 'Grammar & Structures', 'Which sentence correctly uses ''used to'' for past habits?', '["I use to play football every weekend.","I am used to play football every weekend.","I used play football every weekend.","I used to play football every weekend."]'::jsonb, 3),
  ('Intensive English Training', 'Vocabulary Building', 'Choose the word closest in meaning to ''abundant.''', '["Plentiful","Scarce","Silent","Empty"]'::jsonb, 0),
  ('Intensive English Training', 'Vocabulary Building', 'Choose the correct synonym for ''begin.''', '["Delay","Conclude","Commence","Cancel"]'::jsonb, 2),
  ('Intensive English Training', 'Vocabulary Building', 'Which word means the opposite of ''generous''?', '["Stingy","Kind","Helpful","Wealthy"]'::jsonb, 0),
  ('Intensive English Training', 'Vocabulary Building', 'Choose the correct synonym for ''happy.''', '["Joyful","Sad","Tired","Angry"]'::jsonb, 0),
  ('Intensive English Training', 'Vocabulary Building', 'Which word means ''to make something better''?', '["Worsen","Ignore","Improve","Delay"]'::jsonb, 2),
  ('Intensive English Training', 'Vocabulary Building', 'Choose the word closest in meaning to ''huge.''', '["Enormous","Tiny","Average","Narrow"]'::jsonb, 0),
  ('Intensive English Training', 'Vocabulary Building', 'Which word means the opposite of ''difficult''?', '["Hard","Complicated","Easy","Complex"]'::jsonb, 2),
  ('Intensive English Training', 'Vocabulary Building', 'Choose the correct word: ''The manager gave clear ______ for the new project.''', '["instructs","instructions","instructive","instruction''s"]'::jsonb, 1),
  ('Intensive English Training', 'Vocabulary Building', 'Which word best fits: ''She has a ______ vocabulary for someone her age.''', '["remarkably","remarkable","remarked","remark"]'::jsonb, 1),
  ('Intensive English Training', 'Vocabulary Building', 'Choose the correct idiom meaning ''to start over.''', '["Back to square one","Piece of cake","Break a leg","Under the weather"]'::jsonb, 0),
  ('Intensive English Training', 'Vocabulary Building', 'Which word means ''to think carefully about something''?', '["Refuse","Ignore","Consider","Forget"]'::jsonb, 2),
  ('Intensive English Training', 'Vocabulary Building', 'Choose the correct word: ''He was ______ about the results, expecting the worst.''', '["confident","optimistic","pessimistic","careless"]'::jsonb, 2),
  ('Intensive English Training', 'Reading Comprehension', 'When a passage lists advantages then disadvantages, this structure is best called:', '["Compare and contrast","Descriptive only","Chronological","Cause and effect"]'::jsonb, 0),
  ('Intensive English Training', 'Reading Comprehension', 'Skimming a text quickly before reading in detail helps a reader to:', '["Memorize every detail","Get a general sense of the topic and structure","Avoid reading altogether","Translate unfamiliar words"]'::jsonb, 1),
  ('Intensive English Training', 'Reading Comprehension', 'Which best describes ''skimming'' a text?', '["Reading quickly to get the general idea","Translating word by word","Memorizing the whole text","Reading every word slowly"]'::jsonb, 0),
  ('Intensive English Training', 'Reading Comprehension', 'Which best describes ''scanning'' a text?', '["Looking quickly for specific information like a date or name","Summarizing the text","Reading the whole text carefully","Translating the text"]'::jsonb, 0),
  ('Intensive English Training', 'Reading Comprehension', 'A paragraph''s topic sentence usually:', '["Concludes the whole passage","Lists the author''s name","Provides a random detail","States the main idea of the paragraph"]'::jsonb, 3),
  ('Intensive English Training', 'Reading Comprehension', 'Context clues help readers to:', '["Guess the meaning of unfamiliar words from surrounding text","Ignore new vocabulary","Translate a passage word for word","Avoid reading difficult texts"]'::jsonb, 0),
  ('Intensive English Training', 'Reading Comprehension', 'Which is an example of a supporting detail?', '["An unrelated fact","A grammar rule","The title of the passage","A specific example that backs up the main idea"]'::jsonb, 3),
  ('Intensive English Training', 'Reading Comprehension', 'A passage''s ''sequence'' structure typically shows:', '["A cause without an effect","Steps or events in order","A comparison of two things","An opinion with no evidence"]'::jsonb, 1),
  ('Intensive English Training', 'Reading Comprehension', 'Making a prediction while reading involves:', '["Guessing what might happen next based on clues in the text","Reading the last page first only","Memorizing every word","Ignoring the text entirely"]'::jsonb, 0),
  ('Intensive English Training', 'Reading Comprehension', 'Which is the best way to check understanding after reading a paragraph?', '["Summarizing it in your own words","Skipping to the next paragraph immediately","Re-reading without thinking about meaning","Translating it without understanding"]'::jsonb, 0),
  ('Intensive English Training', 'Reading Comprehension', 'An author''s purpose to ''inform'' means the text mainly:', '["Tells a fictional story","Tries to sell a product","Expresses personal feelings only","Provides facts and information on a topic"]'::jsonb, 3),
  ('Intensive English Training', 'Reading Comprehension', 'Which is a sign that a passage is persuasive rather than informative?', '["It tries to convince the reader to agree with an opinion","It has no author","It uses only simple vocabulary","It only lists dates and facts"]'::jsonb, 0),
  ('Intensive English Training', 'Listening Comprehension', 'Listening for ''gist'' means listening for:', '["Every single word spoken","Only numbers mentioned","The general idea of what is being said","Grammar mistakes"]'::jsonb, 2),
  ('Intensive English Training', 'Listening Comprehension', 'Predicting content before listening to an audio clip helps learners to:', '["Translate word-for-word","Focus attention and anticipate vocabulary","Memorize the transcript","Avoid listening at all"]'::jsonb, 1),
  ('Intensive English Training', 'Listening Comprehension', 'Which is a good strategy before listening to an audio clip?', '["Ignoring the questions entirely","Reading the questions first to know what to listen for","Skipping the audio","Closing your eyes and guessing"]'::jsonb, 1),
  ('Intensive English Training', 'Listening Comprehension', 'Listening for specific details means listening for:', '["Only the overall mood","The speaker''s accent","Particular facts like names, numbers, or dates","Background noise"]'::jsonb, 2),
  ('Intensive English Training', 'Listening Comprehension', 'Which best describes ''listening for gist''?', '["Counting how many times a word is repeated","Focusing only on grammar","Memorizing every word","Understanding the general topic or main idea"]'::jsonb, 3),
  ('Intensive English Training', 'Listening Comprehension', 'Note-taking while listening helps learners to:', '["Remember key points for later questions","Translate every word","Ignore important details","Avoid listening carefully"]'::jsonb, 0),
  ('Intensive English Training', 'Listening Comprehension', 'Which of these is a sign of a formal listening context, like a lecture?', '["Structured, academic language and clear organization","Short, one-word answers only","Casual slang throughout","Background music"]'::jsonb, 0),
  ('Intensive English Training', 'Listening Comprehension', 'Predicting vocabulary before listening based on the topic helps learners to:', '["Translate afterward only","Avoid listening at all","Recognize words more easily during the recording","Memorize a script"]'::jsonb, 2),
  ('Intensive English Training', 'Listening Comprehension', 'Which strategy helps when a listening passage is played only once?', '["Skipping the passage","Staying focused and taking quick notes throughout","Guessing without listening","Waiting for a replay"]'::jsonb, 1),
  ('Intensive English Training', 'Listening Comprehension', 'Understanding a speaker''s tone, such as sarcastic or serious, is part of:', '["Listening for background noise","Ignoring the speaker''s intent","Listening for attitude and implied meaning","Listening for spelling only"]'::jsonb, 2),
  ('Intensive English Training', 'Listening Comprehension', 'Which is an example of listening for sequence?', '["Identifying the order of steps in a set of instructions","Ignoring the order of events","Identifying only the speaker''s name","Counting the number of speakers"]'::jsonb, 0),
  ('Intensive English Training', 'Listening Comprehension', 'A common challenge in listening comprehension is:', '["Multiple replays being allowed","Having the transcript available","Too much preparation time","Unfamiliar vocabulary or fast speech rate"]'::jsonb, 3),
  ('Intensive English Training', 'Writing Practice', 'A well-structured paragraph typically begins with:', '["A random detail","A conclusion","A topic sentence stating the main idea","A question with no answer"]'::jsonb, 2),
  ('Intensive English Training', 'Writing Practice', 'Which of these is an appropriate formal greeting in an email?', '["Dear Mr. Kone,","Yo,","Hey!","What''s up,"]'::jsonb, 0),
  ('Intensive English Training', 'Writing Practice', 'Which of these best shows correct paragraph structure?', '["Topic sentence, supporting details, concluding sentence","Only one very long sentence","Random sentences with no order","A list of unrelated facts"]'::jsonb, 0),
  ('Intensive English Training', 'Writing Practice', 'Which is an appropriate way to end a formal letter?', '["Later,","Sincerely,","Bye bye,","See ya,"]'::jsonb, 1),
  ('Intensive English Training', 'Writing Practice', 'Which sentence uses correct capitalization?', '["I visited abidjan last Summer.","i visited abidjan last summer.","I visited Abidjan last summer.","i Visited Abidjan last summer."]'::jsonb, 2),
  ('Intensive English Training', 'Writing Practice', 'A strong essay conclusion should:', '["Ask an unrelated question","Repeat the introduction word for word","Introduce a completely new topic","Summarize the main points and restate the thesis in new words"]'::jsonb, 3),
  ('Intensive English Training', 'Writing Practice', 'Which linking word shows an additional point?', '["Nevertheless","Furthermore","However","Instead"]'::jsonb, 1),
  ('Intensive English Training', 'Writing Practice', 'Proofreading a piece of writing mainly helps to catch:', '["New ideas to add","The overall topic","Grammar, spelling, and punctuation errors","The word count only"]'::jsonb, 2),
  ('Intensive English Training', 'Writing Practice', 'Which of the following is an example of a run-on sentence?', '["After going to the store, I bought bread.","I went to the store, and I bought some bread.","I went to the store I bought some bread.","I went to the store to buy bread."]'::jsonb, 2),
  ('Intensive English Training', 'Writing Practice', 'In formal writing, contractions like ''don''t'' or ''can''t'' should generally be:', '["Written in capital letters","Used as often as possible","Replaced with slang","Avoided in favor of full forms like ''do not'' or ''cannot''"]'::jsonb, 3),
  ('Intensive English Training', 'Writing Practice', 'Which is the best way to organize an essay before writing?', '["Writing without any plan","Skipping the introduction entirely","Memorizing a template essay","Creating a brief outline of main points"]'::jsonb, 3),
  ('Intensive English Training', 'Writing Practice', 'A thesis statement should be placed:', '["In the middle of the conclusion","Near the end of the introduction","In a footnote","Repeated in every paragraph word for word"]'::jsonb, 1),
  ('Intensive English Training', 'Speaking Practice', 'When practicing spoken fluency, learners should focus most on:', '["Avoiding speaking until grammar is perfect","Speaking as fast as possible regardless of clarity","Perfect grammar only, even if it slows speech drastically","Speaking smoothly and expressing ideas clearly, even with minor errors"]'::jsonb, 3),
  ('Intensive English Training', 'Speaking Practice', 'Which is a useful strategy for improving pronunciation?', '["Listening to and imitating native speaker audio regularly","Avoiding listening to native speakers","Memorizing spelling rules only","Only reading silently"]'::jsonb, 0),
  ('Intensive English Training', 'Speaking Practice', 'Which is a good way to practice speaking fluency at home?', '["Memorizing a single script for every topic","Avoiding speaking practice","Only writing essays","Recording yourself speaking on a topic for one minute and reviewing it"]'::jsonb, 3),
  ('Intensive English Training', 'Speaking Practice', 'Which body language supports effective spoken communication?', '["Eye contact and open posture","Crossed arms and looking away","Avoiding all gestures","Speaking with your back turned"]'::jsonb, 0),
  ('Intensive English Training', 'Speaking Practice', 'Which is an effective way to handle an unfamiliar speaking topic?', '["Refusing to answer","Changing the topic abruptly","Repeating the question with no answer","Relating it to something you know and giving a structured answer"]'::jsonb, 3),
  ('Intensive English Training', 'Speaking Practice', 'Filler words like ''um'' and ''uh'' should be:', '["Minimized, though occasional use is natural","Replaced with long pauses","Completely eliminated even in natural speech","Used as much as possible"]'::jsonb, 0),
  ('Intensive English Training', 'Speaking Practice', 'Which helps improve intonation in spoken English?', '["Speaking only in short fragments","Listening to and imitating natural speech patterns","Avoiding all stress on words","Speaking in a flat monotone always"]'::jsonb, 1),
  ('Intensive English Training', 'Speaking Practice', 'A good structure for answering a speaking question is:', '["Answer only ''yes'' or ''no''","Repeat the question without answering","Give a direct answer, then explain with a reason or example","Speak on an unrelated topic"]'::jsonb, 2),
  ('Intensive English Training', 'Speaking Practice', 'Which is a helpful way to expand vocabulary for speaking?', '["Only using memorized phrases","Avoiding new vocabulary","Learning and practicing new words in context regularly","Speaking as little as possible"]'::jsonb, 2),
  ('Intensive English Training', 'Speaking Practice', 'When nervous while speaking, a helpful technique is to:', '["Speak much faster to finish quickly","Stop speaking entirely","Apologize repeatedly and stop","Pause briefly, breathe, and continue calmly"]'::jsonb, 3),
  ('Intensive English Training', 'Speaking Practice', 'Which best supports coherence in a spoken response?', '["Repeating the same sentence","Speaking without any structure","Jumping between unrelated ideas","Organizing ideas logically with clear connectors like ''first'' and ''then''"]'::jsonb, 3),
  ('Intensive English Training', 'Speaking Practice', 'Regular speaking practice with feedback helps learners to:', '["Skip the need for further practice","Identify and correct recurring errors over time","Avoid ever making mistakes","Memorize answers permanently"]'::jsonb, 1),
  ('ESAT', 'Mathematics 1', 'Differentiate f(x) = x^3.', '["3x^2","2x^2","3x","x^2"]'::jsonb, 0),
  ('ESAT', 'Mathematics 1', 'Integrate f(x) = 2x with respect to x.', '["2 + C","x^2/2 + C","x^2 + C","2x^2 + C"]'::jsonb, 2),
  ('ESAT', 'Mathematics 1', 'What is log base 10 of 100?', '["100","10","1","2"]'::jsonb, 3),
  ('ESAT', 'Mathematics 1', 'Solve: 2x^2 - 8 = 0', '["x = 8","x = 2 or x = -2","x = -4","x = 4"]'::jsonb, 1),
  ('ESAT', 'Mathematics 1', 'What is the derivative of f(x) = 5x^2 + 3x?', '["10x + 3","10x","15x^2","5x + 3"]'::jsonb, 0),
  ('ESAT', 'Mathematics 1', 'Simplify: (2x^3)(3x^2)', '["6x^6","6x^5","5x^5","5x^6"]'::jsonb, 1),
  ('ESAT', 'Mathematics 1', 'What is the value of sin(90 degrees)?', '["-1","1","0","0.5"]'::jsonb, 1),
  ('ESAT', 'Mathematics 1', 'Solve for x: log(x) = 2, base 10', '["x = 1000","x = 20","x = 10","x = 100"]'::jsonb, 3),
  ('ESAT', 'Mathematics 1', 'What is the sum of the first 5 positive integers?', '["15","10","25","20"]'::jsonb, 0),
  ('ESAT', 'Mathematics 1', 'Factor: x^2 - 9', '["(x-3)(x+3)","(x+3)^2","(x-9)(x+1)","(x-3)^2"]'::jsonb, 0),
  ('ESAT', 'Mathematics 1', 'What is the gradient, or slope, of a horizontal line?', '["0","Undefined","-1","1"]'::jsonb, 0),
  ('ESAT', 'Mathematics 1', 'Solve the equation: 3^x = 81', '["x = 27","x = 3","x = 9","x = 4"]'::jsonb, 3),
  ('ESAT', 'Physics', 'Unit of force in the SI system?', '["Newton","Joule","Pascal","Watt"]'::jsonb, 0),
  ('ESAT', 'Physics', 'Which quantity is measured in joules?', '["Velocity","Force","Energy","Power"]'::jsonb, 2),
  ('ESAT', 'Physics', 'Acceleration due to gravity near Earth''s surface is approximately:', '["3.6 m/s^2","15 m/s^2","9.8 m/s^2","1.0 m/s^2"]'::jsonb, 2),
  ('ESAT', 'Physics', 'What is the SI unit of energy?', '["Watt","Joule","Newton","Pascal"]'::jsonb, 1),
  ('ESAT', 'Physics', 'Which law states that for every action there is an equal and opposite reaction?', '["Newton''s first law","Law of conservation of mass","Newton''s third law","Newton''s second law"]'::jsonb, 2),
  ('ESAT', 'Physics', 'What is the formula for kinetic energy?', '["m v","1/2 m v^2","F d","m a"]'::jsonb, 1),
  ('ESAT', 'Physics', 'Which of the following is a vector quantity?', '["Speed","Time","Mass","Velocity"]'::jsonb, 3),
  ('ESAT', 'Physics', 'What is the unit of electrical resistance?', '["Watt","Ohm","Volt","Ampere"]'::jsonb, 1),
  ('ESAT', 'Physics', 'Which type of wave requires a medium to travel through?', '["Light waves","Sound waves","X-rays","Radio waves"]'::jsonb, 1),
  ('ESAT', 'Physics', 'What happens to the resistance of a wire as its length increases, all else constant?', '["Resistance becomes zero","Resistance stays the same","Resistance decreases","Resistance increases"]'::jsonb, 3),
  ('ESAT', 'Physics', 'Which quantity is measured in watts?', '["Force","Energy","Power","Momentum"]'::jsonb, 2),
  ('ESAT', 'Physics', 'What is the speed of light in a vacuum approximately?', '["3 x 10^8 m/s","3 x 10^3 m/s","3 x 10^6 m/s","3 x 10^5 m/s"]'::jsonb, 0),
  ('ESAT', 'Chemistry', 'What is the atomic number of Carbon?', '["14","8","6","12"]'::jsonb, 2),
  ('ESAT', 'Chemistry', 'Which particle has a negative charge?', '["Electron","Neutron","Proton","Positron"]'::jsonb, 0),
  ('ESAT', 'Chemistry', 'What is the pH range of a strong acid?', '["Greater than 7","Always 14","Exactly 7","Less than 7"]'::jsonb, 3),
  ('ESAT', 'Chemistry', 'What is the chemical symbol for sodium?', '["Sd","S","Na","So"]'::jsonb, 2),
  ('ESAT', 'Chemistry', 'Which type of bond involves the sharing of electron pairs?', '["Hydrogen bond only","Ionic bond","Covalent bond","Metallic bond"]'::jsonb, 2),
  ('ESAT', 'Chemistry', 'What is the molar mass unit typically expressed in?', '["Moles per second","Grams per liter","Liters per mole","Grams per mole"]'::jsonb, 3),
  ('ESAT', 'Chemistry', 'Which gas is produced when an acid reacts with a metal?', '["Hydrogen gas","Nitrogen gas","Oxygen gas","Carbon dioxide only"]'::jsonb, 0),
  ('ESAT', 'Chemistry', 'What does the pH scale measure?', '["The acidity or alkalinity of a solution","The temperature of a solution","The color of a solution","The density of a solution"]'::jsonb, 0),
  ('ESAT', 'Chemistry', 'Which subatomic particle has no electric charge?', '["Proton","Positron","Electron","Neutron"]'::jsonb, 3),
  ('ESAT', 'Chemistry', 'Which of these is a noble gas?', '["Nitrogen","Oxygen","Neon","Chlorine"]'::jsonb, 2),
  ('ESAT', 'Chemistry', 'What is produced when an acid reacts with a base?', '["Only water vapor","Salt and water","Only a metal","Only a gas"]'::jsonb, 1),
  ('ESAT', 'Chemistry', 'What term describes a substance that speeds up a reaction without being consumed?', '["Catalyst","Reactant","Product","Solvent"]'::jsonb, 0),
  ('ESAT', 'Biology', 'DNA replication occurs during which phase of the cell cycle?', '["G1","G2","S phase","M phase"]'::jsonb, 2),
  ('ESAT', 'Biology', 'Which molecule carries genetic information?', '["Glucose","ATP","Protein only","DNA"]'::jsonb, 3),
  ('ESAT', 'Biology', 'Mitochondria are primarily responsible for:', '["Protein synthesis","Storing genetic material","Producing energy (ATP) for the cell","Photosynthesis"]'::jsonb, 2),
  ('ESAT', 'Biology', 'What is the basic unit of life?', '["Atom","Cell","Organ","Tissue"]'::jsonb, 1),
  ('ESAT', 'Biology', 'Which process do cells use to divide and produce two identical daughter cells?', '["Mitosis","Fertilization","Meiosis","Photosynthesis"]'::jsonb, 0),
  ('ESAT', 'Biology', 'What is the function of red blood cells?', '["Fighting infection","Carrying oxygen throughout the body","Clotting blood","Producing hormones"]'::jsonb, 1),
  ('ESAT', 'Biology', 'Which organ is primarily responsible for filtering blood and producing urine?', '["Liver","Kidney","Lung","Heart"]'::jsonb, 1),
  ('ESAT', 'Biology', 'What is the process by which plants make their own food called?', '["Photosynthesis","Respiration","Digestion","Transpiration"]'::jsonb, 0),
  ('ESAT', 'Biology', 'Which molecule is the primary source of genetic information in cells?', '["Cholesterol","ATP","DNA","Glucose"]'::jsonb, 2),
  ('ESAT', 'Biology', 'What is a population in ecological terms?', '["A group of the same species living in a specific area","A single organism","An entire ecosystem","All species living together"]'::jsonb, 0),
  ('ESAT', 'Biology', 'Which blood type is known as the universal donor?', '["A positive","O negative","B negative","AB positive"]'::jsonb, 1),
  ('ESAT', 'Biology', 'What is the main function of enzymes in the body?', '["Speeding up biochemical reactions","Producing energy directly","Transporting oxygen","Storing genetic information"]'::jsonb, 0),
  ('GRE', 'Verbal Reasoning', 'Choose the word that does not belong: apple, banana, carrot, mango', '["Mango","Banana","Apple","Carrot"]'::jsonb, 3),
  ('GRE', 'Verbal Reasoning', 'Choose the word closest in meaning to ''laconic.''', '["Confused","Angry","Using very few words","Talkative"]'::jsonb, 2),
  ('GRE', 'Verbal Reasoning', 'Complete the analogy: Book is to Library as Painting is to:', '["Paint","Frame","Artist","Museum"]'::jsonb, 3),
  ('GRE', 'Verbal Reasoning', 'Choose the word closest in meaning to ''ephemeral.''', '["Ancient","Permanent","Massive","Short-lived"]'::jsonb, 3),
  ('GRE', 'Verbal Reasoning', 'Choose the word closest in meaning to ''ubiquitous.''', '["Expensive","Hidden","Present everywhere","Rare"]'::jsonb, 2),
  ('GRE', 'Verbal Reasoning', 'Complete the analogy: Doctor is to Hospital as Teacher is to:', '["Pencil","Student","Book","School"]'::jsonb, 3),
  ('GRE', 'Verbal Reasoning', 'Choose the word that best completes: ''Despite his ______ nature, he made a compelling public speaker.''', '["loud","aggressive","reserved","talkative"]'::jsonb, 2),
  ('GRE', 'Verbal Reasoning', 'Choose the word closest in meaning to ''candid.''', '["Confused","Honest and straightforward","Dishonest","Secretive"]'::jsonb, 1),
  ('GRE', 'Verbal Reasoning', 'Choose the word that is the opposite of ''benevolent.''', '["Kind","Friendly","Malevolent","Generous"]'::jsonb, 2),
  ('GRE', 'Verbal Reasoning', 'Complete the analogy: Author is to Book as Composer is to:', '["Instrument","Concert hall","Symphony","Orchestra"]'::jsonb, 2),
  ('GRE', 'Verbal Reasoning', 'Choose the word closest in meaning to ''meticulous.''', '["Careless","Fast","Loud","Extremely careful and precise"]'::jsonb, 3),
  ('GRE', 'Verbal Reasoning', 'Choose the word that best completes: ''The evidence was so ______ that the jury reached a verdict within minutes.''', '["scarce","ambiguous","compelling","irrelevant"]'::jsonb, 2),
  ('GRE', 'Quantitative Reasoning', 'What is 7^2 - 4^2?', '["16","49","45","33"]'::jsonb, 3),
  ('GRE', 'Quantitative Reasoning', 'If x/4 = 9, what is x?', '["4.5","13","9","36"]'::jsonb, 3),
  ('GRE', 'Quantitative Reasoning', 'What is the greatest common divisor of 18 and 24?', '["3","12","9","6"]'::jsonb, 3),
  ('GRE', 'Quantitative Reasoning', 'What is 20% of 150?', '["30","35","25","20"]'::jsonb, 0),
  ('GRE', 'Quantitative Reasoning', 'If 3x = 27, what is x?', '["81","6","3","9"]'::jsonb, 3),
  ('GRE', 'Quantitative Reasoning', 'What is the perimeter of a rectangle with length 10 and width 4?', '["14","40","24","28"]'::jsonb, 3),
  ('GRE', 'Quantitative Reasoning', 'Simplify: (4^2)(4^3)', '["4^6","4^5","16^5","8^5"]'::jsonb, 1),
  ('GRE', 'Quantitative Reasoning', 'What is the average of 5, 10, 15, and 20?', '["20","15","10","12.5"]'::jsonb, 3),
  ('GRE', 'Quantitative Reasoning', 'If a car travels at 60 mph, how far does it travel in 2.5 hours?', '["120 miles","150 miles","100 miles","180 miles"]'::jsonb, 1),
  ('GRE', 'Quantitative Reasoning', 'What is the value of the square root of 144?', '["12","14","10","16"]'::jsonb, 0),
  ('GRE', 'Quantitative Reasoning', 'If x + 5 = 2x - 3, what is x?', '["3","5","2","8"]'::jsonb, 3),
  ('GRE', 'Quantitative Reasoning', 'What is 7/8 as a percentage?', '["80%","75%","87.5%","78%"]'::jsonb, 2),
  ('GRE', 'Analytical Writing', 'The GRE Analytical Writing ''Issue Task'' requires the writer to:', '["Take a position on a general topic and support it","Critique an argument''s logic","Solve a math problem","Summarize a passage"]'::jsonb, 0),
  ('GRE', 'Analytical Writing', 'The GRE ''Argument Task'' asks the writer to:', '["Evaluate the logical soundness of a given argument","State a personal opinion on any topic","Describe a chart","Write a narrative essay"]'::jsonb, 0),
  ('GRE', 'Analytical Writing', 'A strong Issue Task essay typically:', '["Takes a clear position and supports it with reasons and examples","Avoids taking any position","Only summarizes both sides equally with no conclusion","Focuses solely on grammar"]'::jsonb, 0),
  ('GRE', 'Analytical Writing', 'In the Argument Task, identifying unstated assumptions is important because:', '["Assumptions are always correct","The task doesn''t require analysis of assumptions","Assumptions are irrelevant to argument evaluation","The argument''s conclusion often depends on assumptions that may be flawed"]'::jsonb, 3),
  ('GRE', 'Analytical Writing', 'Which of these weakens an argument based on a small sample size?', '["Pointing out that a larger, more representative sample might yield different results","Ignoring the sample size entirely","Providing an unrelated fact","Repeating the original claim"]'::jsonb, 0),
  ('GRE', 'Analytical Writing', 'An effective introduction in the Issue Task should:', '["Clearly state the writer''s position on the issue","Avoid mentioning the topic","Only pose a question with no answer","List every possible counterargument in detail"]'::jsonb, 0),
  ('GRE', 'Analytical Writing', 'Which is considered a logical fallacy the Argument Task might ask you to identify?', '["Correlation being mistaken for causation","A directly cited statistic","A well-supported cause-effect claim","A properly qualified conclusion"]'::jsonb, 0),
  ('GRE', 'Analytical Writing', 'Using specific examples in an Issue Task essay helps to:', '["Avoid answering the prompt","Replace the need for a thesis","Confuse the reader","Support and illustrate the writer''s argument concretely"]'::jsonb, 3),
  ('GRE', 'Analytical Writing', 'A good concluding paragraph in analytical writing should:', '["Reinforce the main argument without simply repeating it word for word","Introduce a brand new argument","Be left out entirely","Contradict the thesis"]'::jsonb, 0),
  ('GRE', 'Analytical Writing', 'In evaluating an argument, considering alternative explanations for the evidence given is:', '["Something to avoid mentioning","Unnecessary and irrelevant","An important critical thinking step","Only relevant in the Issue Task"]'::jsonb, 2),
  ('GRE', 'Analytical Writing', 'Analytical Writing responses are scored on a rubric that considers primarily:', '["Handwriting neatness","Length only, regardless of content","Vocabulary complexity alone","Quality of reasoning, organization, and clarity of expression"]'::jsonb, 3),
  ('UCAT', 'Verbal Reasoning', 'UCAT Verbal Reasoning mainly tests:', '["Memory recall","Spatial awareness","Mathematical calculation","Ability to critically evaluate written information"]'::jsonb, 3),
  ('UCAT', 'Verbal Reasoning', 'Choose the word that does not belong: apple, banana, carrot, mango', '["Apple","Mango","Carrot","Banana"]'::jsonb, 2),
  ('UCAT', 'Verbal Reasoning', 'Choose the word that best completes: ''The report was ______, containing several errors and inconsistencies.''', '["flawless","flawed","authoritative","precise"]'::jsonb, 1),
  ('UCAT', 'Verbal Reasoning', 'In critical reading, identifying an author''s main claim helps you to:', '["Understand the overall argument being made","Ignore supporting details","Memorize vocabulary","Translate the passage"]'::jsonb, 0),
  ('UCAT', 'Verbal Reasoning', 'Choose the word closest in meaning to ''concise.''', '["Repetitive","Vague","Lengthy","Brief and clear"]'::jsonb, 3),
  ('UCAT', 'Verbal Reasoning', 'A passage stating ''while some studies suggest X, others show Y'' demonstrates:', '["A definitive conclusion","An irrelevant detail","Presenting conflicting evidence on a topic","A single unsupported opinion"]'::jsonb, 2),
  ('UCAT', 'Verbal Reasoning', 'Choose the correct meaning of ''infer'' in a reading context.', '["To reach a conclusion based on evidence and reasoning","To ignore the passage","To repeat the passage word for word","To directly state a fact"]'::jsonb, 0),
  ('UCAT', 'Verbal Reasoning', 'Which is an example of evaluating the strength of an argument?', '["Ignoring the argument''s evidence","Repeating the claim without analysis","Checking whether the evidence actually supports the conclusion","Assuming the conclusion is automatically true"]'::jsonb, 2),
  ('UCAT', 'Verbal Reasoning', 'Choose the word closest in meaning to ''ambiguous.''', '["Highly detailed","Perfectly clear","Open to more than one interpretation","Very short"]'::jsonb, 2),
  ('UCAT', 'Verbal Reasoning', 'Which best describes a ''false premise'' in an argument?', '["Strong supporting evidence","A starting assumption that is actually untrue","A well-reasoned inference","A conclusion that logically follows"]'::jsonb, 1),
  ('UCAT', 'Decision Making', 'UCAT Decision Making mainly tests:', '["Memory recall","Handwriting","Logical reasoning and problem solving","Vocabulary"]'::jsonb, 2),
  ('UCAT', 'Decision Making', 'Which of the following best describes a valid logical deduction?', '["A conclusion that necessarily follows from the given premises","A conclusion based on emotion","An opinion stated as fact","A guess with no supporting premises"]'::jsonb, 0),
  ('UCAT', 'Decision Making', 'In a decision-making scenario with incomplete information, the best approach is to:', '["Wait indefinitely for more information","Evaluate the available evidence and make the most reasonable choice","Refuse to decide at all","Choose randomly"]'::jsonb, 1),
  ('UCAT', 'Decision Making', 'Which statement is an example of a syllogism?', '["Some animals are mammals.","Mammals exist.","All mammals are warm-blooded; a dog is a mammal; therefore a dog is warm-blooded.","Dogs are common pets."]'::jsonb, 2),
  ('UCAT', 'Decision Making', 'When interpreting a Venn diagram question, it''s important to:', '["Guess based on the diagram''s color","Ignore the diagram''s labels","Assume all circles are equal in size","Carefully identify overlapping and non-overlapping regions"]'::jsonb, 3),
  ('UCAT', 'Decision Making', 'Which best describes probabilistic reasoning?', '["Assuming all outcomes are equally certain","Making decisions with no data at all","Ignoring probability in decisions","Estimating the likelihood of an outcome based on available information"]'::jsonb, 3),
  ('UCAT', 'Decision Making', 'A ''trade-off'' in decision making refers to:', '["Giving up one benefit to gain another","Choosing the option with zero risk","Having no consequences to a decision","Ignoring alternative choices"]'::jsonb, 0),
  ('UCAT', 'Decision Making', 'Which of the following is a component of good logical reasoning?', '["Assuming the first idea is always correct","Relying only on gut feeling","Ensuring conclusions are supported by valid premises","Ignoring contradictory evidence"]'::jsonb, 2),
  ('UCAT', 'Decision Making', 'In interpreting data tables, it''s important to:', '["Check units and labels carefully before drawing conclusions","Assume all numbers are percentages","Guess values not explicitly given","Ignore the table headers"]'::jsonb, 0),
  ('UCAT', 'Decision Making', 'Which best supports a well-reasoned recommendation?', '["Choosing based on personal preference only","Ignoring any risks involved","Avoiding a decision altogether","Clearly weighing pros and cons based on the evidence available"]'::jsonb, 3),
  ('UCAT', 'Quantitative Reasoning', 'UCAT Quantitative Reasoning mainly tests:', '["Memory recall","Numerical reasoning and problem solving under time pressure","Verbal fluency","Essay writing"]'::jsonb, 1),
  ('UCAT', 'Quantitative Reasoning', 'What is 15% of 80?', '["8","15","10","12"]'::jsonb, 3),
  ('UCAT', 'Quantitative Reasoning', 'What is 25% of 160?', '["40","45","35","30"]'::jsonb, 0),
  ('UCAT', 'Quantitative Reasoning', 'If a train travels 240 km in 4 hours, what is its average speed?', '["70 km/h","60 km/h","50 km/h","80 km/h"]'::jsonb, 1),
  ('UCAT', 'Quantitative Reasoning', 'What is the ratio of 15 to 45 in simplest form?', '["2:3","3:1","1:2","1:3"]'::jsonb, 3),
  ('UCAT', 'Quantitative Reasoning', 'If an item costs 8,000 CFA after a 20% discount, what was its original price?', '["9,000 CFA","8,800 CFA","9,600 CFA","10,000 CFA"]'::jsonb, 3),
  ('UCAT', 'Quantitative Reasoning', 'What is the value of 3/5 of 200?', '["100","90","120","150"]'::jsonb, 2),
  ('UCAT', 'Quantitative Reasoning', 'A rectangle has an area of 48 and a width of 6. What is its length?', '["6","8","12","10"]'::jsonb, 1),
  ('UCAT', 'Quantitative Reasoning', 'What is 60 as a percentage of 240?', '["30%","20%","15%","25%"]'::jsonb, 3),
  ('UCAT', 'Quantitative Reasoning', 'If x : y = 2 : 3 and x = 10, what is y?', '["20","18","15","12"]'::jsonb, 2),
  ('UCAT', 'Situational Judgement', 'UCAT Situational Judgement measures a candidate''s:', '["Physical stamina","Understanding of appropriate behaviour in professional scenarios","Mathematical skill","Reading speed"]'::jsonb, 1),
  ('UCAT', 'Situational Judgement', 'A colleague asks you to cover a shift last minute due to a family emergency. The most appropriate response is to:', '["Report them for asking","Ignore the request entirely","Refuse without explanation","Try to help if possible, or suggest an alternative solution"]'::jsonb, 3),
  ('UCAT', 'Situational Judgement', 'If you notice a colleague making a repeated error that could affect client safety, the most appropriate action is to:', '["Publicly criticize them in front of others","Ignore it since it''s not your job","Raise the concern respectfully with the colleague or a supervisor","Say nothing to avoid conflict"]'::jsonb, 2),
  ('UCAT', 'Situational Judgement', 'A team member takes credit for your idea in a meeting. The most professional response is to:', '["Calmly clarify your contribution afterward or in the moment appropriately","Retaliate by taking credit for their future work","Say nothing and feel resentful indefinitely","Publicly confront them angrily"]'::jsonb, 0),
  ('UCAT', 'Situational Judgement', 'You are running late for an important appointment due to unforeseen circumstances. The best action is to:', '["Arrive without any explanation","Blame someone else for the delay","Simply not show up","Contact the relevant party as soon as possible to inform them"]'::jsonb, 3),
  ('UCAT', 'Situational Judgement', 'A situation requires you to keep a colleague''s personal information confidential. You should:', '["Post about it on social media","Share it if asked casually by others","Respect their privacy and not share the information","Discuss it openly in the break room"]'::jsonb, 2),
  ('UCAT', 'Situational Judgement', 'If you disagree with a supervisor''s decision, the most professional approach is to:', '["Refuse to cooperate at all","Complain to other colleagues instead","Ignore instructions and do your own thing","Respectfully share your perspective through appropriate channels"]'::jsonb, 3),
  ('UCAT', 'Situational Judgement', 'A new team member seems overwhelmed with their workload. An appropriate response is to:', '["Offer support or guidance where appropriate","Ignore their struggle entirely","Criticize their pace publicly","Take over all of their work without discussion"]'::jsonb, 0),
  ('UCAT', 'Situational Judgement', 'You receive conflicting instructions from two supervisors. The best approach is to:', '["Complain without seeking clarification","Guess which instruction to follow","Seek clarification from both to resolve the conflict","Ignore both instructions"]'::jsonb, 2),
  ('UCAT', 'Situational Judgement', 'If you make a mistake at work that affects a colleague, the most appropriate response is to:', '["Blame someone else","Ignore the consequences","Hide the mistake","Acknowledge the mistake and take steps to correct it"]'::jsonb, 3)
) as v(test_name, subject_name, question_text, options, correct_index)
join tests t on t.name = v.test_name
join subjects sub on sub.test_id = t.id and sub.name = v.subject_name
where not exists (
  select 1 from questions q
  where q.subject_id = sub.id and q.question_text = v.question_text
);
